MVCFinal/Controllers/EventController.cs
using MVCFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace MVCFinal.Controllers
{


    public class EventController : Controller
    {
        // GET: Event
        [HttpGet]
        public ActionResult GetEventList()
        {
            List<Event> TD = new List<Event>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8044/api/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                var responseTask = client.GetAsync("event/getallevents");
                responseTask.Wait();

                HttpResponseMessage response = responseTask.Result;
                if (response.IsSuccessStatusCode)
                {
                    // Get back student object
                    var readTask = response.Content.ReadAsAsync<List<Event>>();
                    readTask.Wait();
                    TD = readTask.Result;
                }
            }
            return View(TD);
        }



        [HttpGet]
        public ActionResult AddEvent()
        {
            Event ev = new Event();
            ev.EventDate= DateTime.Now;
            ev.Duration = 1;
            return View(ev);
        }



        [HttpPost]
        public ActionResult AddEvent(Event ev)
        {
            using (var client = new HttpClient())
            {
                if (ModelState.IsValid)
                {
                    client.BaseAddress = new Uri("http://localhost:8044/api/");
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                    var responseTask = client.PostAsJsonAsync(String.Format("event/AddEvent"), ev);
                    responseTask.Wait();

                    HttpResponseMessage response = responseTask.Result;
                    return RedirectToAction("GetEventList");
                }
                return View();
            }
        }

        [HttpGet]
        public ActionResult EditEvent(int eid)
        {
            Event TD = new Event();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8044/api/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                var responseTask = client.GetAsync(String.Format("event/EditEvent/?eid=")+eid);
                responseTask.Wait();

                HttpResponseMessage response = responseTask.Result;
                if (response.IsSuccessStatusCode)
                {
                    // Get back event object
                    var readTask = response.Content.ReadAsAsync<Event>();
                    readTask.Wait();
                    TD = readTask.Result;
                }
            }
            return View(TD);
        }

        [HttpPost]
        public ActionResult EditEvent(Event ev)
        {
            List<Event> TD = new List<Event>();

            using (var client = new HttpClient())
            {
                if (ModelState.IsValid) 
                { 
                client.BaseAddress = new Uri("http://localhost:8044/api/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                var responseTask = client.PutAsJsonAsync(String.Format("event/EditEvent"), ev);
                responseTask.Wait();

                HttpResponseMessage response = responseTask.Result;
                   
                    return RedirectToAction("GetEventList");
                }
                return View();
            }
            
        }
        
        [HttpGet]
        public ActionResult DeleteEvent(int eid)
        {
            Event TD = new Event();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8044/api/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                var responseTask = client.GetAsync("event/DeleteEvent/?eid="+eid);
                responseTask.Wait();

                HttpResponseMessage response = responseTask.Result;
                if (response.IsSuccessStatusCode)
                {
                    // Get back Event object
                    var readTask = response.Content.ReadAsAsync<Event>();
                    readTask.Wait();
                    TD = readTask.Result;
                }
            }
            return View(TD);
        }

        [HttpPost,ActionName("DeleteEvent")]
        public ActionResult DeleteEvents(int eid)
        {
            List<Event> TD = new List<Event>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:8044/api/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                var responseTask = client.DeleteAsync(String.Format("event/DeleteEventss/?eid="+eid));
                responseTask.Wait();

                HttpResponseMessage response = responseTask.Result;
               
            }
            return RedirectToAction("GetEventList");
        }
    }
}

MVCFinal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCFinal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCFinal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCFinal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCFinal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    @RenderPage("~/Views/Event/NavBar.cshtml")


}

<title>Home Page</title>
<html>
<head>
    <style>
        body {
            background-image: url(../../Images/back.jpg);
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            
        }

        .name {
            position:absolute;
            width: 563px;
            height: 154px;
            left: 980px;
            top: 150px;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            font-style: normal;
            font-weight: 400;
            font-size: 128px;
            line-height: 154px;
            color: #000000;
        }

        .tagline {
            position: fixed;
            width: 665px;
            height: 48px;
            left: 940px;
            top: 380px;
            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            font-style: normal;
            font-weight: 400;
            font-size: 32px;
            line-height: 48px;
            color: #FFFFFF;
        }

        .view {
            position: absolute;
            width: 290px;
            height: 78px;
            left: 800px;
            top: 510px;
            background: #B3B3B3;
            font-size: 25px;
        }

        .add {
            position: absolute;
            width: 290px;
            height: 78px;
            left: 1230px;
            top: 510px;
            background: #B3B3B3;
            font-size: 25px;
        }
    </style>
</head>
<p class="name">Evento</p>
<p class="tagline">Events at your finger tips!!</p>
<button type="button" class="view" onclick="location.href='@Url.Action("GetEventList", "Event")'"><b>View Events</b></button>
<button type="button" class="add" onclick="location.href='@Url.Action("AddEvent", "Event")'"><b>Add Events</b></button>
</html>